# -*- coding: utf-8 -*-
"""Toronto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLnoF9ExUfRXDErVmhQFgGCqVy96aF9o

We are loading the CSV files
"""

import pandas as pd
import os

# Define the directory where files are uploaded
upload_dir = '/content/'

# List all files in the directory
all_files = os.listdir(upload_dir)

# Filter for CSV files starting with 'SR'
csv_files = [f for f in all_files if f.startswith('SR') and f.endswith('.csv')]

# Create a dictionary to store DataFrames
dataframes = {}

print("Loading the following CSV files:")
for filename in csv_files:
    filepath = os.path.join(upload_dir, filename)
    try:
        # Extract the year from the filename (e.g., SR2020.csv -> 2020)
        year = filename[2:6]
        df = pd.read_csv(filepath)
        dataframes[year] = df
        print(f" - {filename} loaded as 'dataframes[{year}]'")
    except Exception as e:
        print(f"Error loading {filename}: {e}")

print("\nAll loaded dataframes are accessible via the 'dataframes' dictionary. For example, to access 2020 data: 'dataframes['2020']'")

"""we are splitting data into train and test"""

from sklearn.model_selection import train_test_split

# Lists to hold train and test dataframes from each year
all_train_dfs = []
all_test_dfs = []

# Loop through each DataFrame in the 'dataframes' dictionary
print("Splitting data into train and test sets for each year...")
for year, df in dataframes.items():
    # Split each DataFrame into 80% train and 20% test
    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
    all_train_dfs.append(train_df)
    all_test_dfs.append(test_df)
    print(f" - {year}: Train size = {len(train_df)}, Test size = {len(test_df)}")

# Concatenate all train dataframes into a single dataframe
combined_train_df = pd.concat(all_train_dfs, ignore_index=True)
print(f"\nCombined training data size: {len(combined_train_df)}")

# Concatenate all test dataframes into a single dataframe
combined_test_df = pd.concat(all_test_dfs, ignore_index=True)
print(f"Combined test data size: {len(combined_test_df)}")

# Save the combined dataframes to new CSV files
combined_train_df.to_csv('combined_train.csv', index=False)
combined_test_df.to_csv('combined_test.csv', index=False)

print("\nData successfully split and saved to 'combined_train.csv' and 'combined_test.csv'.")

!pip install catboost

"""For predicting with 311 data, several machine learning models could be suitable, depending on the specific prediction task (e.g., classification of request type, regression for resolution time, etc.) and the nature of your data (e.g., text descriptions, categorical fields, numerical values). Here are some good candidates:

Gradient Boosting Machines (e.g., XGBoost, LightGBM, CatBoost): These are often top performers for tabular data. They are robust, handle various data types well, and can capture complex non-linear relationships.
Random Forests: An ensemble method that is generally very accurate and handles both numerical and categorical features effectively. They are also less prone to overfitting compared to single decision trees.
Logistic Regression: A good baseline model for binary or multi-class classification tasks. It's highly interpretable and computationally efficient.
Support Vector Machines (SVMs): Effective in high-dimensional spaces and for tasks where clear separation between classes exists.
Neural Networks (Deep Learning): If your 311 data includes a lot of unstructured text (e.g., complaint descriptions), deep learning models like Recurrent Neural Networks (RNNs) or Transformer-based models could be very powerful for feature extraction and prediction. For tabular data, simple feed-forward neural networks can also be effective.
Time Series Models (e.g., ARIMA, Prophet): If your prediction involves forecasting future request volumes or resolution times based on historical patterns, dedicated time series models would be appropriate.
"""

combined_train_df.head()

# List all unique service categories to understand what we can predict
unique_services = combined_train_df['Service Request Type'].unique()
print(f"Found {len(unique_services)} unique service types. Here are the top 20:")
print(combined_train_df['Service Request Type'].value_counts().head(20))

def prepare_category_data(df, category_keyword):
    """Filters data by category and aggregates counts by date."""
    # Ensure date is datetime
    df['Creation Date'] = pd.to_datetime(df['Creation Date'])

    # Filter for the specific category (e.g., 'Tree', 'Animal', 'Pothole')
    filtered_df = df[df['Service Request Type'].str.contains(category_keyword, case=False, na=False)].copy()

    # Aggregate by date
    daily_counts = filtered_df.groupby(filtered_df['Creation Date'].dt.date).size().reset_index(name='Request_Count')
    daily_counts.columns = ['Date', 'Request_Count']
    daily_counts['Date'] = pd.to_datetime(daily_counts['Date'])

    # Feature Engineering for May 1st prediction
    daily_counts['Month'] = daily_counts['Date'].dt.month
    daily_counts['Day'] = daily_counts['Date'].dt.day
    daily_counts['DayOfWeek'] = daily_counts['Date'].dt.dayofweek

    return daily_counts

# Example: Prepare data for Tree related requests
tree_data = prepare_category_data(combined_train_df, 'Tree')
print("Daily volume for Tree-related requests:")
display(tree_data.head())

import numpy as np
from catboost import CatBoostRegressor

# 1. Prepare Pothole data specifically
pothole_data = prepare_category_data(combined_train_df, 'Pot hole')

# 2. Simulate Weather Data for demonstration
# In a real use case, you would join this with actual weather history
np.random.seed(42)
pothole_data['IsRaining'] = np.random.choice([0, 1], size=len(pothole_data), p=[0.7, 0.3])

# 3. Define Features and Target for the regression
features = ['Month', 'Day', 'DayOfWeek', 'IsRaining']
X = pothole_data[features]
y = pothole_data['Request_Count']

# 4. Train the CatBoost Regressor
model_pothole = CatBoostRegressor(iterations=200, learning_rate=0.05, depth=4, verbose=0)
model_pothole.fit(X, y)

# 5. Predict for May 1st (Month=5, Day=1)
# We'll assume a generic DayOfWeek (e.g., 2 for Wednesday)
may_1st_no_rain = pd.DataFrame([[5, 1, 2, 0]], columns=features)
may_1st_rain = pd.DataFrame([[5, 1, 2, 1]], columns=features)

pred_no_rain = model_pothole.predict(may_1st_no_rain)[0]
pred_rain = model_pothole.predict(may_1st_rain)[0]

print(f"Predicted Pothole requests for May 1st (No Rain): {round(pred_no_rain)}")
print(f"Predicted Pothole requests for May 1st (With Rain): {round(pred_rain)}")

import pandas as pd
import numpy as np
from catboost import CatBoostRegressor

# 1. Load the weather data
weather_df = pd.read_csv('/content/weatherstats_toronto_daily.csv')
# Ensure the date column is in datetime format and matches the format in our request data
weather_df['date'] = pd.to_datetime(weather_df['date'])

# 2. Prepare the target category data (e.g., Potholes)
pothole_data = prepare_category_data(combined_train_df, 'Pot hole')
pothole_data['Date'] = pd.to_datetime(pothole_data['Date'])

# 3. Merge request data with real weather data
# We'll use 'precipitation' or 'rain' column from the weather file.
# I'll create an 'IsRaining' flag based on precipitation > 0.
merged_data = pd.merge(pothole_data, weather_df[['date', 'precipitation']], left_on='Date', right_on='date', how='inner')
merged_data['IsRaining'] = (merged_data['precipitation'] > 0).astype(int)

# 4. Define Features and Target
features = ['Month', 'Day', 'DayOfWeek', 'IsRaining']
X = merged_data[features]
y = merged_data['Request_Count']

# 5. Train the CatBoost Regressor on real data
model_real_weather = CatBoostRegressor(iterations=300, learning_rate=0.05, depth=6, verbose=0)
model_real_weather.fit(X, y)

# 6. Predict for May 1st (assuming a generic year/day of week)
# Feature order: [Month, Day, DayOfWeek, IsRaining]
may_1st_no_rain = pd.DataFrame([[5, 1, 2, 0]], columns=features)
may_1st_rain = pd.DataFrame([[5, 1, 2, 1]], columns=features)

pred_no_rain = model_real_weather.predict(may_1st_no_rain)[0]
pred_rain = model_real_weather.predict(may_1st_rain)[0]

print(f"Prediction using REAL weather data for May 1st:")
print(f" - Expected requests if dry: {round(pred_no_rain)}")
print(f" - Expected requests if raining: {round(pred_rain)}")

def prepare_snow_model(df, weather_path):
    # 1. Load weather
    w_df = pd.read_csv(weather_path, low_memory=False)
    w_df['date'] = pd.to_datetime(w_df['date'])

    # Identify correct snow columns
    snow_cols = [c for c in w_df.columns if 'snow' in c.lower()]
    print(f"Found snow-related columns: {snow_cols}")

    depth_col = next((c for c in snow_cols if 'ground' in c.lower() or 'depth' in c.lower()), None)
    precip_col = next((c for c in snow_cols if 'fall' in c.lower() or 'precip' in c.lower()), 'precipitation')

    # 2. Prepare Snow requests
    snow_requests = prepare_category_data(df, 'Snow')

    # 3. Merge
    weather_cols = list(set(['date', 'precipitation', depth_col, precip_col]))
    weather_cols = [c for c in weather_cols if c in w_df.columns]
    merged = pd.merge(snow_requests, w_df[weather_cols], left_on='Date', right_on='date', how='inner')

    # Normalize names for model
    if depth_col: merged = merged.rename(columns={depth_col: 'snow_depth'})
    else: merged['snow_depth'] = 0
    if precip_col and precip_col != 'precipitation': merged = merged.rename(columns={precip_col: 'snow_precipitation'})
    else: merged['snow_precipitation'] = merged.get('precipitation', 0)

    merged[['snow_depth', 'snow_precipitation']] = merged[['snow_depth', 'snow_precipitation']].fillna(0)
    return merged

snow_merged_data = prepare_snow_model(combined_train_df, '/content/weatherstats_toronto_daily.csv')
features_snow = ['Month', 'DayOfWeek', 'snow_depth', 'snow_precipitation']
X_snow = snow_merged_data[features_snow]
y_snow = snow_merged_data['Request_Count']
model_snow = CatBoostRegressor(iterations=300, verbose=0)
model_snow.fit(X_snow, y_snow)
print('Snow prediction model trained successfully.')

def predict_snow_event(model, start_month, start_day_of_week, snow_depth_cm, duration_days):
    total_predicted = 0
    print(f'Predicting for a {duration_days}-day event with {snow_depth_cm}cm snow depth:')
    for day in range(duration_days):
        current_day_of_week = (start_day_of_week + day) % 7
        input_data = pd.DataFrame([[
            start_month,
            current_day_of_week,
            snow_depth_cm,
            snow_depth_cm / 5
        ]], columns=['Month', 'DayOfWeek', 'snow_depth', 'snow_precipitation'])
        daily_pred = model.predict(input_data)[0]
        total_predicted += max(0, daily_pred)
        print(f' - Day {day+1} (DoW {current_day_of_week}): {round(daily_pred)} requests')
    return round(total_predicted)

total_requests = predict_snow_event(model_snow, start_month=1, start_day_of_week=0, snow_depth_cm=50, duration_days=3)
print(f'\nTotal predicted snow requests over 3 days: {total_requests}')

"""### 1. Road Pothole Model (Rain Impact)
We will train a model specifically for 'Pot hole' requests using actual historical rain data.
"""

def train_pothole_model_v2(df, weather_path):
    w_df = pd.read_csv(weather_path, low_memory=False)
    w_df['date'] = pd.to_datetime(w_df['date'])

    # Sort weather to calculate lags
    w_df = w_df.sort_values('date')
    # Create lagged features (rain from 1, 2, and 3 days ago)
    w_df['precip_lag1'] = w_df['precipitation'].shift(1)
    w_df['precip_lag2'] = w_df['precipitation'].shift(2)
    w_df['precip_lag3'] = w_df['precipitation'].shift(3)

    pothole_data = prepare_category_data(df, 'Pot hole')
    weather_cols = ['date', 'precipitation', 'precip_lag1', 'precip_lag2', 'precip_lag3']
    merged = pd.merge(pothole_data, w_df[weather_cols], left_on='Date', right_on='date', how='inner')
    merged = merged.fillna(0)

    features = ['Month', 'DayOfWeek', 'precipitation', 'precip_lag1', 'precip_lag2', 'precip_lag3']
    X = merged[features]
    y = merged['Request_Count']

    model = CatBoostRegressor(iterations=300, verbose=0)
    model.fit(X, y)
    return model

model_pothole_lagged = train_pothole_model_v2(combined_train_df, '/content/weatherstats_toronto_daily.csv')

print('Lagged Pothole model trained. Predicting for cumulative impact of rain (10cm over 3 days):')
# Testing a scenario where it rained 33mm each day for 3 days (total ~100mm or 10cm)
test_input = pd.DataFrame([[5, 2, 33, 33, 33, 33]], columns=['Month', 'DayOfWeek', 'precipitation', 'precip_lag1', 'precip_lag2', 'precip_lag3'])
pred = model_pothole_lagged.predict(test_input)[0]
print(f' - Predicted requests after sustained heavy rain: {round(pred)}')

import matplotlib.pyplot as plt
import seaborn as sns

# Let's check the actual correlation in the merged data
correlation = merged_data[['Request_Count', 'precipitation']].corr()
print("Correlation between Daily Rain and Pothole Requests:")
print(correlation)

# Visualize the relationship
plt.figure(figsize=(10, 6))
sns.scatterplot(data=merged_data, x='precipitation', y='Request_Count', alpha=0.5)
plt.title('Daily Precipitation vs. Pothole Requests')
plt.xlabel('Precipitation (mm)')
plt.ylabel('Number of Requests')
plt.grid(True)
plt.show()

# Check the max rain in the training data
max_rain_trained = merged_data['precipitation'].max()
print(f"Max rain seen in training data: {max_rain_trained}mm")
print(f"Note: 50cm rain is 500mm, which is likely an extreme outlier or 'out-of-bounds' for the model.")

"""### Weekly Cumulative Rain vs. Next-Week Potholes
We will now aggregate weather data into weekly sums and shift the pothole request data to see if heavy rain in week $N$ predicts high pothole volume in week $N+1$.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Prepare Daily Data
w_df = pd.read_csv('/content/weatherstats_toronto_daily.csv', low_memory=False)
w_df['date'] = pd.to_datetime(w_df['date'])
pothole_counts = prepare_category_data(combined_train_df, 'Pot hole')

# 2. Merge Daily
daily_merged = pd.merge(pothole_counts, w_df[['date', 'precipitation']], left_on='Date', right_on='date')
daily_merged = daily_merged.sort_values('Date').set_index('Date')

# 3. Resample to Weekly (Sum precipitation, Sum requests)
weekly_data = daily_merged.resample('W').agg({
    'precipitation': 'sum',
    'Request_Count': 'sum'
})

# 4. Create the 'Next Week' Target
# We want to predict Next Week's requests using Current Week's rain
weekly_data['rain_this_week'] = weekly_data['precipitation']
weekly_data['potholes_next_week'] = weekly_data['Request_Count'].shift(-1)

# Drop the last row as it won't have a 'next week'
weekly_analysis = weekly_data.dropna()

# 5. Visualize Correlation
plt.figure(figsize=(10, 6))
sns.regplot(data=weekly_analysis, x='rain_this_week', y='potholes_next_week', scatter_kws={'alpha':0.5})
plt.title('Weekly Cumulative Rain vs. Pothole Requests (Following Week)')
plt.xlabel('Cumulative Rain this Week (mm)')
plt.ylabel('Pothole Requests Next Week')
plt.grid(True)
plt.show()

corr = weekly_analysis['rain_this_week'].corr(weekly_analysis['potholes_next_week'])
print(f'Correlation coefficient: {corr:.4f}')

from catboost import CatBoostRegressor

# Prepare features for the weekly model
weekly_analysis['Month'] = weekly_analysis.index.month

features_weekly = ['Month', 'rain_this_week']
X_w = weekly_analysis[features_weekly]
y_w = weekly_analysis['potholes_next_week']

model_weekly = CatBoostRegressor(iterations=500, learning_rate=0.05, depth=4, verbose=0)
model_weekly.fit(X_w, y_w)

# Predict for a scenario: 100mm rain in a week (10cm)
test_weekly = pd.DataFrame([[5, 100]], columns=features_weekly)
pred_weekly = model_weekly.predict(test_weekly)[0]

print(f'Predicted pothole requests for the week following 10cm of rain: {round(pred_weekly)}')

"""### Weekly Cumulative Rain vs. Potholes (2-Week Lag)
We are shifting the target variable by 2 weeks to see if rain in week $N$ correlates more strongly with requests in week $N+2$.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Reuse existing daily_merged data
# 2. Resample to Weekly
weekly_data_2lag = daily_merged.resample('W').agg({
    'precipitation': 'sum',
    'Request_Count': 'sum'
})

# 3. Create the '2nd Week After' Target
weekly_data_2lag['rain_this_week'] = weekly_data_2lag['precipitation']
# shift(-2) means today's rain is mapped to requests happening 2 intervals (weeks) later
weekly_data_2lag['potholes_2_weeks_later'] = weekly_data_2lag['Request_Count'].shift(-2)

# Drop NaNs created by shifting
weekly_2lag_analysis = weekly_data_2lag.dropna().copy()

# 4. Visualize
plt.figure(figsize=(10, 6))
sns.regplot(data=weekly_2lag_analysis, x='rain_this_week', y='potholes_2_weeks_later', scatter_kws={'alpha':0.5}, color='teal')
plt.title('Weekly Rain vs. Pothole Requests (2-Week Lag)')
plt.xlabel('Cumulative Rain this Week (mm)')
plt.ylabel('Pothole Requests 2nd Week After')
plt.grid(True)
plt.show()

corr_2w = weekly_2lag_analysis['rain_this_week'].corr(weekly_2lag_analysis['potholes_2_weeks_later'])
print(f'Correlation coefficient (2-week lag): {corr_2w:.4f}')

from catboost import CatBoostRegressor

# Prepare features for the 2-week lag model
weekly_2lag_analysis['Month'] = weekly_2lag_analysis.index.month

features_2w = ['Month', 'rain_this_week']
X_2w = weekly_2lag_analysis[features_2w]
y_2w = weekly_2lag_analysis['potholes_2_weeks_later']

model_2w = CatBoostRegressor(iterations=500, learning_rate=0.05, depth=4, verbose=0)
model_2w.fit(X_2w, y_2w)

# Predict for the 10cm rain scenario
test_2w = pd.DataFrame([[5, 100]], columns=features_2w)
pred_2w = model_2w.predict(test_2w)[0]

print(f'Predicted pothole requests for the week occurring 2 weeks after 10cm of rain: {round(pred_2w)}')

"""### Weekly Cumulative Rain vs. Potholes (3 and 4-Week Lags)
Testing if the impact of heavy rain on road infrastructure takes nearly a month to fully manifest as service requests.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Reuse existing daily_merged data
# 2. Resample to Weekly
weekly_extended = daily_merged.resample('W').agg({
    'precipitation': 'sum',
    'Request_Count': 'sum'
})

# 3. Create shifted targets
weekly_extended['rain_this_week'] = weekly_extended['precipitation']
weekly_extended['potholes_3w_lag'] = weekly_extended['Request_Count'].shift(-3)
weekly_extended['potholes_4w_lag'] = weekly_extended['Request_Count'].shift(-4)

# Clean data for each lag
analysis_3w = weekly_extended[['rain_this_week', 'potholes_3w_lag']].dropna()
analysis_4w = weekly_extended[['rain_this_week', 'potholes_4w_lag']].dropna()

# 4. Visualization
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

sns.regplot(data=analysis_3w, x='rain_this_week', y='potholes_3w_lag', ax=ax1, scatter_kws={'alpha':0.4}, color='orange')
ax1.set_title('3-Week Lag: Rain vs Potholes')
ax1.set_xlabel('Rain this Week (mm)')
ax1.set_ylabel('Requests 3 Weeks Later')

sns.regplot(data=analysis_4w, x='rain_this_week', y='potholes_4w_lag', ax=ax2, scatter_kws={'alpha':0.4}, color='red')
ax2.set_title('4-Week Lag: Rain vs Potholes')
ax2.set_xlabel('Rain this Week (mm)')
ax2.set_ylabel('Requests 4 Weeks Later')

plt.tight_layout()
plt.show()

# 5. Correlations
print(f'Correlation coefficient (3-week lag): {analysis_3w.corr().iloc[0,1]:.4f}')
print(f'Correlation coefficient (4-week lag): {analysis_4w.corr().iloc[0,1]:.4f}')

"""### Relationship between Monthly Snowfall and Pothole Requests
We will examine if higher snowfall months correlate with higher pothole request volumes, looking for a potential seasonal lag.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Prepare Pothole and Weather data
pothole_counts = prepare_category_data(combined_train_df, 'Pot hole')
w_df = pd.read_csv('/content/weatherstats_toronto_daily.csv', low_memory=False)
w_df['date'] = pd.to_datetime(w_df['date'])

# 2. Extract Snowfall (assuming 'snow' column exists or using precipitation if not)
snow_col = 'snow' if 'snow' in w_df.columns else 'precipitation'

# 3. Merge and Resample to Monthly
merged_daily = pd.merge(pothole_counts, w_df[['date', snow_col]], left_on='Date', right_on='date')
merged_daily['Month_Year'] = merged_daily['Date'].dt.to_period('M')

monthly_agg = merged_daily.groupby('Month_Year').agg({
    snow_col: 'sum',
    'Request_Count': 'sum'
}).reset_index()

# 4. Correlation by Month of Year (Seasonal check)
monthly_agg['Month'] = monthly_agg['Month_Year'].dt.month
seasonal_pattern = monthly_agg.groupby('Month').mean().reset_index()

# 5. Plotting
fig, ax1 = plt.subplots(figsize=(12, 6))

ax1.set_xlabel('Month')
ax1.set_ylabel('Avg Monthly Snowfall (cm/mm)', color='tab:blue')
sns.barplot(x='Month', y=snow_col, data=seasonal_pattern, ax=ax1, color='tab:blue', alpha=0.6)
ax1.tick_params(axis='y', labelcolor='tab:blue')

ax2 = ax1.twinx()
ax2.set_ylabel('Avg Monthly Pothole Requests', color='tab:red')
sns.lineplot(x=seasonal_pattern.index, y='Request_Count', data=seasonal_pattern, ax=ax2, color='tab:red', marker='o', linewidth=3)
ax2.tick_params(axis='y', labelcolor='tab:red')

plt.title('Average Monthly Snowfall vs. Pothole Requests (Seasonal Pattern)')
plt.xticks(range(12), ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.show()

# Calculate correlation
monthly_corr = monthly_agg[[snow_col, 'Request_Count']].corr().iloc[0,1]
print(f'Overall Monthly Snowfall-to-Pothole Correlation: {monthly_corr:.4f}')

"""### Weekly Cumulative Snow vs. Next-Week Potholes
Following the same logic as our rain analysis, we will see if heavy snow in one week predicts a spike in pothole reports the following week.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Prepare Daily Data
w_df = pd.read_csv('/content/weatherstats_toronto_daily.csv', low_memory=False)
w_df['date'] = pd.to_datetime(w_df['date'])
pothole_counts = prepare_category_data(combined_train_df, 'Pot hole')

# Identify snow column
snow_col = 'snow' if 'snow' in w_df.columns else 'precipitation'

# 2. Merge and Resample to Weekly
daily_merged_snow = pd.merge(pothole_counts, w_df[['date', snow_col]], left_on='Date', right_on='date')
daily_merged_snow = daily_merged_snow.sort_values('Date').set_index('Date')

weekly_snow_data = daily_merged_snow.resample('W').agg({
    snow_col: 'sum',
    'Request_Count': 'sum'
})

# 3. Create the 'Next Week' Target
weekly_snow_data['snow_this_week'] = weekly_snow_data[snow_col]
weekly_snow_data['potholes_next_week'] = weekly_snow_data['Request_Count'].shift(-1)

# Drop NaNs
weekly_snow_analysis = weekly_snow_data.dropna()

# 4. Visualize Correlation
plt.figure(figsize=(10, 6))
sns.regplot(data=weekly_snow_analysis, x='snow_this_week', y='potholes_next_week', scatter_kws={'alpha':0.5}, color='blue')
plt.title('Weekly Cumulative Snow vs. Pothole Requests (Following Week)')
plt.xlabel('Cumulative Snow this Week (cm/mm)')
plt.ylabel('Pothole Requests Next Week')
plt.grid(True)
plt.show()

corr_snow = weekly_snow_analysis['snow_this_week'].corr(weekly_snow_analysis['potholes_next_week'])
print(f'Correlation coefficient (Weekly Snow vs Next Week Potholes): {corr_snow:.4f}')

"""### Geospatial Analysis: Pothole Requests by Postal Code (FSA)
We will group the requests by the first three characters of the postal code to identify high-volume areas.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Filter for Pothole requests in the training data
pothole_geo = combined_train_df[combined_train_df['Service Request Type'].str.contains('Pot hole', case=False, na=False)].copy()

# 2. Count requests by Postal Code (First 3 characters)
postal_counts = pothole_geo['First 3 Chars of Postal Code'].value_counts().reset_index()
postal_counts.columns = ['FSA', 'Request_Count']

# 3. Visualize the Top 25 Postal Codes
plt.figure(figsize=(14, 7))
sns.barplot(data=postal_counts.head(25), x='FSA', y='Request_Count', palette='magma', hue='FSA', legend=False)
plt.title('Top 25 FSAs for Pothole Requests in Toronto')
plt.xlabel('Postal Code (First 3 Chars)')
plt.ylabel('Total Requests')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Display the top 10 for reference
print("Top 10 Postal Code areas with highest pothole reports:")
display(postal_counts.head(10))

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Filter for Pothole requests and clean Ward names
pothole_ward = combined_train_df[combined_train_df['Service Request Type'].str.contains('Pot hole', case=False, na=False)].copy()

# 2. Count requests by Ward
ward_counts = pothole_ward['Ward'].value_counts().reset_index()
ward_counts.columns = ['Ward', 'Pothole_Request_Count']

# 3. Visualize Pothole requests by Ward
plt.figure(figsize=(12, 10))
sns.barplot(data=ward_counts, y='Ward', x='Pothole_Request_Count', palette='viridis')
plt.title('Pothole Requests by Toronto Ward')
plt.xlabel('Number of Requests')
plt.ylabel('Ward Name')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Display top 10 most affected wards
print("Top 10 Wards for Pothole Requests:")
display(ward_counts.head(10))

"""### Ward Sensitivity Analysis
We can also look at the proportion of pothole requests relative to the total requests in each ward to see if potholes are a disproportionately large issue for specific areas.
"""

# 1. Total requests per ward
total_ward_volume = combined_train_df['Ward'].value_counts().reset_index()
total_ward_volume.columns = ['Ward', 'Total_Volume']

# 2. Merge with pothole counts
ward_sensitivity = pd.merge(ward_counts, total_ward_volume, on='Ward')
ward_sensitivity['Pothole_Percentage'] = (ward_sensitivity['Pothole_Request_Count'] / ward_sensitivity['Total_Volume']) * 100

# 3. Sort by percentage to find 'pothole-heavy' wards
ward_sensitivity = ward_sensitivity.sort_values(by='Pothole_Percentage', ascending=False)

print("Wards with the highest percentage of pothole requests relative to total volume:")
display(ward_sensitivity[['Ward', 'Pothole_Request_Count', 'Pothole_Percentage']].head(10))

import folium
import json
import requests
import pandas as pd

# 1. Filter and Aggregate pothole data
pothole_geo = combined_train_df[combined_train_df['Service Request Type'].str.contains('Pot hole', case=False, na=False)].copy()
ward_counts = pothole_geo['Ward'].value_counts().reset_index()
ward_counts.columns = ['Ward_Name', 'Pothole_Request_Count']

# 2. Fetch Toronto 25-Ward GeoJSON from a stable GitHub mirror
# This mirror provides the 2018-present 25-ward structure
geojson_url = "https://raw.githubusercontent.com/jdupuis/toronto_ward_boundaries/master/toronto_wards_2018_25.geojson"

try:
    response = requests.get(geojson_url)
    if response.status_code == 200:
        geojson_data = response.json()

        # 3. Create Map centered on Toronto
        m = folium.Map(location=[43.7181, -79.3760], zoom_start=11, tiles='CartoDB positron')

        # 4. Add Choropleth
        # AREA_NAME in this GeoJSON matches the Ward names in our DataFrame (e.g., 'Toronto-St. Paul\'s (12)')
        folium.Choropleth(
            geo_data=geojson_data,
            name='choropleth',
            data=ward_counts,
            columns=['Ward_Name', 'Pothole_Request_Count'],
            key_on='feature.properties.AREA_NAME',
            fill_color='YlOrRd',
            fill_opacity=0.7,
            line_opacity=0.2,
            legend_name='Pothole Requests (Toronto Wards)'
        ).add_to(m)

        display(m)
    else:
        print(f"Could not reach GeoJSON mirror (Status {response.status_code}). Falling back to table.")
        display(ward_counts.head(10))
except Exception as e:
    print(f"Map Error: {e}")
    display(ward_counts.head(10))

"""We can also see if certain postal codes are more sensitive to weather than others by checking the average daily volume per FSA.

### 2. Snow Clearing Model (Snow Impact)
Using the previously prepared snow data to predict requests based on snow depth.
"""

print('--- ROAD POTHOLES (Rain Impact) ---')
# Simulating 3 days of sustained rain totaling the target amount
for rain_cm in range(10, 60, 10):
    daily_mm = (rain_cm * 10) / 3
    test_input = pd.DataFrame([[5, 2, daily_mm, daily_mm, daily_mm, daily_mm]],
                              columns=['Month', 'DayOfWeek', 'precipitation', 'precip_lag1', 'precip_lag2', 'precip_lag3'])
    pred = model_pothole_lagged.predict(test_input)[0]
    print(f' - Total Rain {rain_cm}cm (over 3 days): {round(pred)} requests')

print('\n--- SNOW CLEARING (Snow Impact) ---')
for snow_cm in range(10, 60, 10):
    pred = predict_snow_event(model_snow, start_month=1, start_day_of_week=0, snow_depth_cm=snow_cm, duration_days=1)
    print(f' - Snow Depth {snow_cm}cm: {pred} requests')

import numpy as np
from catboost import CatBoostRegressor

# 1. Prepare Pothole data
pothole_data = prepare_category_data(combined_train_df, 'Pot hole')

# 2. Simulate Weather Data (Since we don't have a real weather file)
# In a real scenario, you would load this from a CSV
np.random.seed(42)
pothole_data['IsRaining'] = np.random.choice([0, 1], size=len(pothole_data), p=[0.7, 0.3])

# 3. Define Features and Target
features = ['Month', 'Day', 'DayOfWeek', 'IsRaining']
X = pothole_data[features]
y = pothole_data['Request_Count']

# 4. Train a Regressor
model_pothole = CatBoostRegressor(iterations=200, learning_rate=0.05, depth=4, verbose=0)
model_pothole.fit(X, y)

# 5. Predict for May 1st (Month=5, Day=1)
# DayOfWeek for May 1st depends on the year, let's assume a generic weekday (e.g., 2 for Wednesday)
may_1st_no_rain = pd.DataFrame([[5, 1, 2, 0]], columns=features)
may_1st_rain = pd.DataFrame([[5, 1, 2, 1]], columns=features)

pred_no_rain = model_pothole.predict(may_1st_no_rain)[0]
pred_rain = model_pothole.predict(may_1st_rain)[0]

print(f"Predicted Pothole requests for May 1st (No Rain): {round(pred_no_rain)}")
print(f"Predicted Pothole requests for May 1st (With Rain): {round(pred_rain)}")

"""### How to predict for May 1st with Rain
To fulfill your request, you need to add a `Rain` column to the `tree_data` (or any other category) DataFrame.

Once you have that, you can train a model where:
- **Features**: `Month`, `Day`, `DayOfWeek`, `IsRaining` (binary)
- **Target**: `Request_Count`

You would then ask the model to predict the count for `Month=5`, `Day=1` while toggling `IsRaining` between 0 and 1.
"""

