"use client";
import { motion, useReducedMotion } from "motion/react";
import { Sparkles } from "lucide-react";
import { RecommendationCard } from "@/components/shared/recommendation-card";

type Recommendation = {
  text: string;
  drivers?: string[];
  wardIds?: string[];
};

type InsightCardProps = {
  children: React.ReactNode;
  eyebrow?: string;
  recommendation?: Recommendation;
};

/**
 * The "money shot" (designsystem.md §6): an eyebrow → chart → recommendation
 * callout, revealed with a subtle stagger. Wraps any generative UI component.
 */
export function InsightCard({
  children,
  eyebrow = "Generated by 311 Pulse",
  recommendation,
}: InsightCardProps) {
  const reduce = useReducedMotion();

  const container = {
    hidden: {},
    show: {
      transition: { staggerChildren: reduce ? 0 : 0.08, delayChildren: reduce ? 0 : 0.04 },
    },
  };
  const item = {
    hidden: { opacity: 0, y: reduce ? 0 : 12 },
    show: {
      opacity: 1,
      y: 0,
      transition: { type: "spring" as const, stiffness: 320, damping: 30 },
    },
  };

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="my-1">
      <motion.div
        variants={item}
        className="flex items-center gap-1.5 px-1 pb-1 text-[9px] font-black uppercase tracking-widest text-primary"
      >
        <Sparkles className="h-3 w-3" />
        {eyebrow}
      </motion.div>

      <motion.div variants={item}>{children}</motion.div>

      {recommendation && (
        <motion.div variants={item}>
          <RecommendationCard
            text={recommendation.text}
            drivers={recommendation.drivers}
            wardIds={recommendation.wardIds}
          />
        </motion.div>
      )}
    </motion.div>
  );
}
